# **Part 1**

In [5]:
#1
df=pd.read_csv('AWCustomers.csv')
df

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,NaN,Grace,C,Bailey,NaN,6627 Camelback Ct.,NaN,Coronado,California,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953,2017-03-06
18357,11459,NaN,Tasha,NaN,Deng,NaN,9627 Kendall Rd,NaN,Port Macquarie,New South Wales,...,Bachelors,Skilled Manual,F,S,0,2,0,0,60992,2017-03-06
18358,12160,NaN,Jaclyn,NaN,Zhang,NaN,4364 Viera Avenue,NaN,Beaverton,Oregon,...,Partial College,Skilled Manual,F,S,0,2,0,0,51859,2017-03-06
18359,14353,NaN,Erin,I,Reed,NaN,3866 Mt. Everest Court,NaN,Vancouver,British Columbia,...,High School,Clerical,F,S,0,0,0,0,87177,2017-03-06
18360,16676,NaN,Amanda,NaN,Perry,NaN,7870 Orangewood Dr.,NaN,Grossmont,California,...,Graduate Degree,Professional,F,M,1,2,0,0,136856,2017-03-06

In [4]:
import pandas as pd
df = pd.read_csv("AWCustomers.csv", usecols=["CustomerID", "City", "Occupation", "NumberCarsOwned", "YearlyIncome"])
print("Data to predict future bike buyers :")
df

Data to predict future bike buyers :

,CustomerID,City,Occupation,NumberCarsOwned,YearlyIncome
0,21173,Wollongong,Clerical,3,81916
1,13249,Shawnee,Clerical,2,81076
2,29350,West Covina,Clerical,3,86387
3,13503,Liverpool,Skilled Manual,2,61481
4,22803,Werne,Skilled Manual,1,51804
...,...,...,...,...,...
18356,25414,Coronado,Skilled Manual,1,52953
18357,11459,Port Macquarie,Skilled Manual,2,60992
18358,12160,Beaverton,Skilled Manual,2,51859
18359,14353,Vancouver,Clerical,0,87177
18360,16676,Grossmont,Professional,2,136856



1. CustomerID: Discrete, Nominal
2. PostalCode: Discrete, Nominal
3. BirthDate: Continuous, Interval
4. Education: Discrete, Ordinal
5. Occupation: Discrete, Nominal
6. Gender: Discrete, Nominal
7. MaritalStatus: Discrete, Nominal
8. HomeOwnerFlag: Discrete, Nominal
9. NumberCarsOwned: Discrete, Ratio
10. NumberChildrenAtHome: Discrete, Ratio
11. TotalChildren: Discrete, Ratio
12. YearlyIncome: Continuous, Ratio
13. BikeBuyer: Discrete, Nominal
14. AvgMonthSpend: Continuous, Ratio

# Part **2**

In [6]:
#2
import pandas as pd
df=pd.read_csv('AWCustomers.csv')
print(pd.isna(df))

       CustomerID  Title  FirstName  MiddleName  LastName  Suffix  \
0           False   True      False       False     False    True
1           False   True      False        True     False    True
2           False   True      False        True     False    True
3           False   True      False        True     False    True
4           False   True      False       False     False    True
...           ...    ...        ...         ...       ...     ...
18356       False   True      False       False     False    True
18357       False   True      False        True     False    True
18358       False   True      False        True     False    True
18359       False   True      False       False     False    True
18360       False   True      False        True     False    True

       AddressLine1  AddressLine2   City  StateProvinceName  ...  Education  \
0             False          True  False              False  ...      False
1             False          True  False              False  ...      False
2             False          True  False              False  ...      False
3             False          True  False              False  ...      False
4             False          True  False              False  ...      False
...             ...           ...    ...                ...  ...        ...
18356         False          True  False              False  ...      False
18357         False          True  False              False  ...      False
18358         False          True  False              False  ...      False
18359         False          True  False              False  ...      False
18360         False          True  False              False  ...      False

       Occupation  Gender  MaritalStatus  HomeOwnerFlag  NumberCarsOwned  \
0           False   False          False          False            False
1           False   False          False          False            False
2           False   False          False          False            False
3           False   False          False          False            False
4           False   False          False          False            False
...           ...     ...            ...            ...              ...
18356       False   False          False          False            False
18357       False   False          False          False            False
18358       False   False          False          False            False
18359       False   False          False          False            False
18360       False   False          False          False            False

       NumberChildrenAtHome  TotalChildren  YearlyIncome  LastUpdated
0                     False          False         False        False
1                     False          False         False        False
2                     False          False         False        False
3                     False          False         False        False
4                     False          False         False        False
...                     ...            ...           ...          ...
18356                 False          False         False        False
18357                 False          False         False        False
18358                 False          False         False        False
18359                 False          False         False        False
18360                 False          False         False        False

[18361 rows x 24 columns]

In [7]:
df.drop(['Title'],axis=1,inplace=True)
df.drop(['Suffix'],axis=1,inplace=True)
df.drop(['AddressLine2'],axis=1,inplace=True)
df

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,Chad,C,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,Ryan,NaN,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,Julia,NaN,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,Theodore,NaN,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,Marshall,J,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,Grace,C,Bailey,6627 Camelback Ct.,Coronado,California,United States,92118,292-555-0130,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953,2017-03-06
18357,11459,Tasha,NaN,Deng,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1 (11) 500 555-0171,...,Bachelors,Skilled Manual,F,S,0,2,0,0,60992,2017-03-06
18358,12160,Jaclyn,NaN,Zhang,4364 Viera Avenue,Beaverton,Oregon,United States,97005,819-555-0110,...,Partial College,Skilled Manual,F,S,0,2,0,0,51859,2017-03-06
18359,14353,Erin,I,Reed,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,791-555-0118,...,High School,Clerical,F,S,0,0,0,0,87177,2017-03-06
18360,16676,Amanda,NaN,Perry,7870 Orangewood Dr.,Grossmont,California,United States,91941,553-555-0122,...,Graduate Degree,Professional,F,M,1,2,0,0,136856,2017-03-06

In [8]:
import numpy as np
from sklearn.impute import SimpleImputer
df['MiddleName'] = df['MiddleName'].fillna(df['MiddleName'].mode().iloc[0])
df

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,Chad,C,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,Ryan,A,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,Julia,A,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,Theodore,A,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,Marshall,J,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,Grace,C,Bailey,6627 Camelback Ct.,Coronado,California,United States,92118,292-555-0130,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953,2017-03-06
18357,11459,Tasha,A,Deng,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1 (11) 500 555-0171,...,Bachelors,Skilled Manual,F,S,0,2,0,0,60992,2017-03-06
18358,12160,Jaclyn,A,Zhang,4364 Viera Avenue,Beaverton,Oregon,United States,97005,819-555-0110,...,Partial College,Skilled Manual,F,S,0,2,0,0,51859,2017-03-06
18359,14353,Erin,I,Reed,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,791-555-0118,...,High School,Clerical,F,S,0,0,0,0,87177,2017-03-06
18360,16676,Amanda,A,Perry,7870 Orangewood Dr.,Grossmont,California,United States,91941,553-555-0122,...,Graduate Degree,Professional,F,M,1,2,0,0,136856,2017-03-06

# **Part 2 (b)**

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df['YearlyIncome']=scaler.fit_transform(df['YearlyIncome'].values.reshape(-1,1)).flatten()
df

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,Chad,C,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,...,Bachelors,Clerical,M,M,1,3,0,1,0.496842,2017-03-06
1,13249,Ryan,A,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,...,Partial College,Clerical,M,M,1,2,1,2,0.489453,2017-03-06
2,29350,Julia,A,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,...,Bachelors,Clerical,F,S,0,3,0,0,0.536172,2017-03-06
3,13503,Theodore,A,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,...,Partial College,Skilled Manual,M,M,1,2,1,2,0.317083,2017-03-06
4,22803,Marshall,J,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,...,Partial College,Skilled Manual,M,S,1,1,0,0,0.231958,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,Grace,C,Bailey,6627 Camelback Ct.,Coronado,California,United States,92118,292-555-0130,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,0.242065,2017-03-06
18357,11459,Tasha,A,Deng,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1 (11) 500 555-0171,...,Bachelors,Skilled Manual,F,S,0,2,0,0,0.312781,2017-03-06
18358,12160,Jaclyn,A,Zhang,4364 Viera Avenue,Beaverton,Oregon,United States,97005,819-555-0110,...,Partial College,Skilled Manual,F,S,0,2,0,0,0.232442,2017-03-06
18359,14353,Erin,I,Reed,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,791-555-0118,...,High School,Clerical,F,S,0,0,0,0,0.543121,2017-03-06
18360,16676,Amanda,A,Perry,7870 Orangewood Dr.,Grossmont,California,United States,91941,553-555-0122,...,Graduate Degree,Professional,F,M,1,2,0,0,0.980128,2017-03-06

# **Part 2 (c)**

In [11]:
import pandas as pd
import numpy as np
bins=np.linspace(min(df['YearlyIncome']),max(df['YearlyIncome']),4)
group_names=['Level1','Level2','Level3']
df['YearlyIncome']=pd.cut(df['YearlyIncome'],bins,group_names,include_lowest=True)
df

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,Chad,C,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,...,Bachelors,Clerical,M,M,1,3,0,1,"(0.333, 0.667]",2017-03-06
1,13249,Ryan,A,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,...,Partial College,Clerical,M,M,1,2,1,2,"(0.333, 0.667]",2017-03-06
2,29350,Julia,A,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,...,Bachelors,Clerical,F,S,0,3,0,0,"(0.333, 0.667]",2017-03-06
3,13503,Theodore,A,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,...,Partial College,Skilled Manual,M,M,1,2,1,2,"(-0.001, 0.333]",2017-03-06
4,22803,Marshall,J,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,...,Partial College,Skilled Manual,M,S,1,1,0,0,"(-0.001, 0.333]",2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,Grace,C,Bailey,6627 Camelback Ct.,Coronado,California,United States,92118,292-555-0130,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,"(-0.001, 0.333]",2017-03-06
18357,11459,Tasha,A,Deng,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1 (11) 500 555-0171,...,Bachelors,Skilled Manual,F,S,0,2,0,0,"(-0.001, 0.333]",2017-03-06
18358,12160,Jaclyn,A,Zhang,4364 Viera Avenue,Beaverton,Oregon,United States,97005,819-555-0110,...,Partial College,Skilled Manual,F,S,0,2,0,0,"(-0.001, 0.333]",2017-03-06
18359,14353,Erin,I,Reed,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,791-555-0118,...,High School,Clerical,F,S,0,0,0,0,"(0.333, 0.667]",2017-03-06
18360,16676,Amanda,A,Perry,7870 Orangewood Dr.,Grossmont,California,United States,91941,553-555-0122,...,Graduate Degree,Professional,F,M,1,2,0,0,"(0.667, 1.0]",2017-03-06

# **Part 2 (d)**

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['NumberCarsOwned'] = scaler.fit_transform(df['NumberCarsOwned'].values.reshape(-1, 1)).flatten()
df

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,Chad,C,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,...,Bachelors,Clerical,M,M,1,1.892524,0,1,"(0.333, 0.667]",2017-03-06
1,13249,Ryan,A,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,...,Partial College,Clerical,M,M,1,0.798389,1,2,"(0.333, 0.667]",2017-03-06
2,29350,Julia,A,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,...,Bachelors,Clerical,F,S,0,1.892524,0,0,"(0.333, 0.667]",2017-03-06
3,13503,Theodore,A,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,...,Partial College,Skilled Manual,M,M,1,0.798389,1,2,"(-0.001, 0.333]",2017-03-06
4,22803,Marshall,J,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,...,Partial College,Skilled Manual,M,S,1,-0.295746,0,0,"(-0.001, 0.333]",2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,Grace,C,Bailey,6627 Camelback Ct.,Coronado,California,United States,92118,292-555-0130,...,Graduate Degree,Skilled Manual,F,M,0,-0.295746,0,2,"(-0.001, 0.333]",2017-03-06
18357,11459,Tasha,A,Deng,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1 (11) 500 555-0171,...,Bachelors,Skilled Manual,F,S,0,0.798389,0,0,"(-0.001, 0.333]",2017-03-06
18358,12160,Jaclyn,A,Zhang,4364 Viera Avenue,Beaverton,Oregon,United States,97005,819-555-0110,...,Partial College,Skilled Manual,F,S,0,0.798389,0,0,"(-0.001, 0.333]",2017-03-06
18359,14353,Erin,I,Reed,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,791-555-0118,...,High School,Clerical,F,S,0,-1.389881,0,0,"(0.333, 0.667]",2017-03-06
18360,16676,Amanda,A,Perry,7870 Orangewood Dr.,Grossmont,California,United States,91941,553-555-0122,...,Graduate Degree,Professional,F,M,1,0.798389,0,0,"(0.667, 1.0]",2017-03-06

# **Part 2 (e)**

In [16]:
from sklearn.preprocessing import OneHotEncoder
columns = ['Education',	'Occupation',	'Gender',	'MaritalStatus'	]

encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = encoder.fit_transform(df[columns])
one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(columns))
df_encoded = pd.concat([df, one_hot_df], axis=1)
df_encoded = df_encoded.drop(columns, axis=1)
df_encoded

,CustomerID,FirstName,MiddleName,LastName,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,PhoneNumber,...,Education_Partial High School,Occupation_Clerical,Occupation_Management,Occupation_Manual,Occupation_Professional,Occupation_Skilled Manual,Gender_F,Gender_M,MaritalStatus_M,MaritalStatus_S
0,21173,Chad,C,Yuan,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1 (11) 500 555-0115,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,13249,Ryan,A,Perry,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,787-555-0136,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,29350,Julia,A,Thompson,1774 Tice Valley Blvd.,West Covina,California,United States,91791,120-555-0111,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,13503,Theodore,A,Gomez,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1 (11) 500 555-0167,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
4,22803,Marshall,J,Shan,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1 (11) 500 555-0113,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,Grace,C,Bailey,6627 Camelback Ct.,Coronado,California,United States,92118,292-555-0130,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
18357,11459,Tasha,A,Deng,9627 Kendall Rd,Port Macquarie,New South Wales,Australia,2444,1 (11) 500 555-0171,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
18358,12160,Jaclyn,A,Zhang,4364 Viera Avenue,Beaverton,Oregon,United States,97005,819-555-0110,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
18359,14353,Erin,I,Reed,3866 Mt. Everest Court,Vancouver,British Columbia,Canada,V7L 4J4,791-555-0118,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
18360,16676,Amanda,A,Perry,7870 Orangewood Dr.,Grossmont,California,United States,91941,553-555-0122,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

# **Part 3**

In [13]:
a =  df['TotalChildren']
b = df['HomeOwnerFlag']
c = list(set(a) & set(b))
d = list(set(a) | set(b))
J = float(len(c)+len(d)/len(d))
print("Simple Matching :",J)

Simple Matching : 3.0

In [14]:
a= df['TotalChildren']
b= df['HomeOwnerFlag']
c= list(set(a) & set(b))
d= list(set(a) | set(b))
J=float(len(c)/len(d))
print("Jaccard Similarity :",J)

Jaccard Similarity : 0.5

In [15]:
import numpy as np
from numpy.linalg import norm
a =  df['TotalChildren']
b = df['HomeOwnerFlag']
cosine = np.dot(a,b)/(norm(a)*norm(b))
print("Cosine Similarity :",cosine)

Cosine Similarity : 0.7940586649666289

# **Part 3 (b)**

In [9]:
import pandas as pd
import numpy as np
c = np.corrcoef(df['NumberCarsOwned'],df['YearlyIncome'])
c

array([[1.        , 0.47730015],
       [0.47730015, 1.        ]])